Update action.yml for capturing digest

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -26,25 +26,32 @@ runs:
       name: Publish Helm chart
       uses: docker://alpine/helm:3.15.2
       run: |
-        set -x
+        set -u
         CHART_NAME="$(helm show chart "$CHART" | grep -E '^name: ' | sed -E 's/^name: //')"
         CHART_VERSION="$(helm show chart "$CHART" | grep -E '^version: ' | sed -E 's/^version: //')"
-        CHART_DIGEST="$(helm show chart "$CHART" | grep -E '^digest: ' | sed -E 's/^digest: //')"
-        echo $CHART_DIGEST
         printf %s "${REMOTE}/${CHART_NAME}" > $CLOUDBEES_OUTPUTS/chart
         printf %s "${CHART_VERSION}" > $CLOUDBEES_OUTPUTS/version
         set -x
-        helm push "$CHART" "$REMOTE"
-        
-        # Publish build artifact
-        response=$(curl --fail-with-body  -X 'POST' "$URL/v2/workflows/runs/artifactinfos" -H "Authorization: Bearer $API_TOKEN" -H 'Content-Type: application/json' --data-binary '{"runId":"'"$RUN_ID"'","runAttempt":'$RUN_ATTEMPT',"name":"'"$CHART_NAME"'","version":"'"$CHART_VERSION"'","url":"'"$REMOTE"/"$CHART_NAME":"$CHART_VERSION"'","type":"helm"}') || command_failed=1
-        # Check curl exit code
-        if [ ${command_failed:-0} -eq 1 ];
-        then
-          echo "Platform API call failed with error '$response'"
-          exit 1
+        helm_push_output=${helm push "$CHART" "$REMOTE"}
+        if [[ $? -eq 0 ]]; then
+            echo "Chart pushed successfully!"
+            # Extract the digest
+            digest=$(echo "$helm_push_output" | grep -i 'Digest' | awk '{print $2}')
+            echo "Digest: $digest"
+            # Publish build artifact
+            response=$(curl --fail-with-body  -X 'POST' "$URL/v2/workflows/runs/artifactinfos" -H "Authorization: Bearer $API_TOKEN" -H 'Content-Type: application/json' --data-binary '{"runId":"'"$RUN_ID"'","runAttempt":'$RUN_ATTEMPT',"name":"'"$CHART_NAME"'","version":"'"$CHART_VERSION"'","url":"'"$REMOTE"/"$CHART_NAME":"$CHART_VERSION"'","type":"helm","digest":"'$digest'"}') || command_failed=1
+            # Check curl exit code
+            if [ ${command_failed:-0} -eq 1 ];
+            then
+              echo "Platform API call failed with error '$response'"
+              exit 1
+            else
+              echo "Artifact details pushed to platform successfully"
+            fi
         else
-          echo "Artifact details pushed to platform successfully"
+            echo "Failed to push the chart."
+            echo "Error: $output"
+            exit 1
         fi  
       env:
         CHART: ${{ inputs.chart }}
